### PR TITLE
Hypbld 162/templatize name

### PR DESCRIPTION
**Pull request by markturansky**
start a basic spawner/provisioner of trex instances

### CODE REVIEW

**Comment by markturansky** [comment]
```
$ make test-integration
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go install -ldflags="" ./cmd/trex
OCM_ENV=testing gotestsum --format short-verbose -- -p 1 -ldflags -s -v -timeout 1h  \
		./test/integration
I1107 11:38:11.331475   87411 framework.go:72] Initializing testing environment
I1107 11:38:11.648048   87411 framework.go:151] Using Mock OCM Authz Client
I1107 11:38:11.648056   87411 framework.go:176] Disabling Sentry error reporting
I1107 11:38:11.651779   87411 api_server.go:145] Serving without TLS at localhost:8000
PASS test/integration.TestDinosaurGet (0.37s)
PASS test/integration.TestDinosaurPost (0.26s)
PASS test/integration.TestDinosaurPatch (0.27s)
PASS test/integration.TestDinosaurPaging (0.31s)
PASS test/integration.TestDinosaurListSearch (0.29s)
PASS test/integration.TestUpdateDinosaurWithRacingRequests (0.34s)
PASS test/integration.TestUpdateDinosaurWithRacingRequests_WithoutLock (0.29s)
I1107 11:38:13.780427   87411 api_server.go:151] Web server terminated
PASS test/integration (cached)

DONE 7 tests in 0.226s

```

**Comment by markturansky** [comment]
```

★ mturansk:~/projects/src/github.com/openshift-online/rh-trex  
$ make test
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go install -ldflags="" ./cmd/trex
OCM_ENV=testing gotestsum --format short-verbose -- -p 1 -v  \
        ./pkg/... \
        ./cmd/...
EMPTY pkg/api
EMPTY pkg/api/openapi
EMPTY pkg/api/presenters
EMPTY pkg/auth
EMPTY pkg/client/ocm
PASS pkg/config.TestConfigReadStringFile (0.00s)
PASS pkg/config.TestConfigReadIntFile (0.00s)
PASS pkg/config.TestConfigReadBoolFile (0.00s)
PASS pkg/config.TestConfigReadQuotedFile (0.00s)
PASS pkg/config
PASS pkg/controllers.TestControllerFramework (0.00s)
PASS pkg/controllers
EMPTY pkg/dao
EMPTY pkg/dao/mocks
EMPTY pkg/db
EMPTY pkg/db/db_context
EMPTY pkg/db/db_session
EMPTY pkg/db/migrations
EMPTY pkg/db/mocks
EMPTY pkg/db/transaction
PASS pkg/errors.TestErrorFormatting (0.00s)
PASS pkg/errors.TestErrorFind (0.00s)
PASS pkg/errors
EMPTY pkg/handlers
EMPTY pkg/logger
PASS pkg/services.TestDinosaurFindBySpecies (0.00s)
PASS pkg/services.TestSQLTranslation (0.00s)
PASS pkg/services
EMPTY pkg/util
EMPTY cmd/trex
EMPTY cmd/trex/clone
PASS cmd/trex/environments.TestLoadServices (0.36s)
PASS cmd/trex/environments
EMPTY cmd/trex/migrate
EMPTY cmd/trex/servecmd
EMPTY cmd/trex/server
EMPTY cmd/trex/server/logging

DONE 10 tests in 3.014s

★ mturansk:~/projects/src/github.com/openshift-online/rh-trex  
$ make test-integration
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go install -ldflags="" ./cmd/trex
OCM_ENV=testing gotestsum --format short-verbose -- -p 1 -ldflags -s -v -timeout 1h  \
                ./test/integration
I1107 15:41:10.305033  114514 framework.go:72] Initializing testing environment
I1107 15:41:10.548386  114514 framework.go:151] Using Mock OCM Authz Client
I1107 15:41:10.548394  114514 framework.go:176] Disabling Sentry error reporting
I1107 15:41:10.552706  114514 api_server.go:145] Serving without TLS at localhost:8000
PASS test/integration.TestControllerRacing (1.39s)
PASS test/integration.TestDinosaurGet (0.36s)
PASS test/integration.TestDinosaurPost (0.26s)
PASS test/integration.TestDinosaurPatch (0.24s)
PASS test/integration.TestDinosaurPaging (0.29s)
PASS test/integration.TestDinosaurListSearch (0.28s)
PASS test/integration.TestUpdateDinosaurWithRacingRequests (0.32s)
PASS test/integration.TestUpdateDinosaurWithRacingRequests_WithoutLock (0.28s)
I1107 15:41:13.985646  114514 api_server.go:151] Web server terminated
PASS test/integration

DONE 8 tests in 4.536s
```

**Comment by gurnben** [comment]
Investigating the CI failures now

**Review by MacdonEm — APPROVED** [review]
/lgtm

**Pull request merged**
