### PR TITLE
Patch introduces the changes to run performance tests in RHTAP.

### PR DESCRIPTION
**Pull request by yogananth-subramanian**
Within RHTAP, an ephemeral environment (namespace), will be used to temporarily deploy and run performance tests.A custom deployment, a devfile.yaml that points to  Kubernetes YAML(deploy.yaml) file and Dockerfile(Containerfile.rhtap), will be used for deployment to the ephemeral environment. The pipeline .tekton/rhtap-perf-integration-test.yaml runs performance test in the ephemeral environment and does regression analysis by querying and  pushing the results to the horreum.

### CODE REVIEW

**Comment by markturansky** [comment]
adding a _new_ deployment template like this means we'll have to keep two up to date with any changes.  is it possible to use instead templates/service-template.yaml?

**Comment by yogananth-subramanian** [comment]
> adding a _new_ deployment template like this means we'll have to keep two up to date with any changes. is it possible to use instead templates/service-template.yaml?

Hello @markturansky 
It seems Konflux supports using only one kubernetes deployment file in the devfile spec. So, if we want to use templates under templates/path, they need to be merged into a single file.

If we could consolidate the db-template.yml, route-template.yml, secret-template.yml, and service-template.yml into a single file, we could reuse the same for Konflux deployment.

**Comment by yogananth-subramanian** [comment]
Hello @markturansky @gurnben , Have updated the PR to reuse the exiting deployment files in the repo, and  to  accommodate the new architectural changes in konflux. If you could review the latest patch, that would be great.

**Review by markturansky — APPROVED** [review]
LGTM

**Pull request merged**
